services:
  postgres:
    image: postgres:17
    container_name: shopverse-postgres
    environment:
      POSTGRES_DB: shopverse
      POSTGRES_USER: shopverse
      POSTGRES_PASSWORD: shopverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: