spring.datasource.url=jdbc:postgresql://localhost:5432/kadaplatz
spring.datasource.username=kadaplatz
spring.datasource.password=kadaplatz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true