spring.datasource.url=jdbc:postgresql://localhost:5432/kadaplatz
spring.datasource.username=kadaplatz
spring.datasource.password=kadaplatz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=S2FkYVBsYXR6Snd0U2VjcmV0S2V5Rm9yTGVhcm5pbmdQdXJwb3NlT25seTIwMjY=
app.jwt.expiration-ms=3600000
app.admin.email=admin@kadaplatz.dev
app.admin.password=Admin123!